{
 "title": "API + PostgreSQL Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "State Timeline (PostgreSQL)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  alert_level AS D001\r\nFROM temperature_alerts\r\nWHERE device_id = 'D001'\r\nORDER BY timestamp DESC"
    },
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  alert_level AS D002\r\nFROM temperature_alerts\r\nWHERE device_id = 'D002'\r\nORDER BY timestamp DESC"
    },
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  $__time(timestamp),\r\n  alert_level AS D003\r\nFROM temperature_alerts\r\nWHERE device_id = 'D003'\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "D001 (PostgreSQL)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  temperature AS value\r\nFROM temperature_alerts\r\nWHERE device_id = 'D001'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "D002 (MySQl)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  temperature AS value\r\nFROM temperature_alerts\r\nWHERE device_id = 'D001'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "D003 (MySQl)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_db",
     "rawSql": "SELECT\r\n  temperature AS value\r\nFROM temperature_alerts\r\nWHERE device_id = 'D003'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Sate Timeline (API)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.*.timestamp", "type": "time" },
      { "jsonPath": "$.*.alert_level", "language": "jsonpath", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/alert/D001"
    },
    {
     "fields": [
      { "jsonPath": "$.*.timestamp", "type": "time" },
      { "jsonPath": "$.*.alert_level", "language": "jsonpath", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/alert/D002"
    },
    {
     "fields": [
      { "jsonPath": "$.*.timestamp", "type": "time" },
      { "jsonPath": "$.*.alert_level", "language": "jsonpath", "name": " ", "type": "string" }
     ],
     "method": "GET",
     "urlPath": "/alert/D003"
    }
   ]
  },
  {
   "title": "D001 (API)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.0.temperature", "name": "", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/alert/D001"
    }
   ]
  },
  {
   "title": "D002 (API)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.0.temperature", "name": "", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/alert/D002"
    }
   ]
  },
  {
   "title": "D003 (API)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.0.temperature", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/alert/D003"
    }
   ]
  }
 ]
}