-- PostgreSQL initialization script for sensor data storage

\connect sensor_db;

-- Raw temperature data (Node-RED -> PostgreSQL)
CREATE TABLE IF NOT EXISTS temperature_data (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   VARCHAR(20)   NOT NULL,
    temperature NUMERIC(5, 2) NOT NULL,
    timestamp   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Alert data (Alert Manager -> PostgreSQL)
CREATE TABLE IF NOT EXISTS temperature_alerts (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp   TIMESTAMPTZ   NOT NULL,
    device_id   VARCHAR(20)   NOT NULL,
    temperature NUMERIC(5, 2) NOT NULL,
    alert_level VARCHAR(200)  NOT NULL
);

-- Indexes for faster Grafana queries
CREATE INDEX IF NOT EXISTS idx_td_device ON temperature_data (device_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_ta_device ON temperature_alerts (device_id, timestamp);
